
services:
  backend:
    image: ${REGISTRY}/${IMAGE_NAME}-backend:${TAG}
    restart: always
    depends_on:
      - parser
      - db
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_NAME: can-i-cai

  frontend:
    image: ${REGISTRY}/${IMAGE_NAME}-frontend:${TAG}
    restart: always
    depends_on:
      - backend

  db:
    image: mongo
    volumes:
      - databasedata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  parser:
    image: ${REGISTRY}/${IMAGE_NAME}-parser:${TAG}
    depends_on:
     - db
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_NAME: can-i-cai

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  databasedata:
