services:
  backend:
    image: node:20.14
    depends_on:
      - parser
      - db
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./shared:/shared
    ports:
      - '3000:3000'
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
    command: sh -c "npm install && npm run dev"

  frontend:
    image: node:20.14
    depends_on:
      - backend
    working_dir: /app
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - ./shared:/shared
    command: sh -c "npm install && npm run dev"

  db:
    image: mongo
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - databasedata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  parser:
    image: node:20.14
    depends_on:
     - db
    working_dir: /app
    volumes:
      - ./parser:/app
      - ./shared:/shared
      - ./data:/app/data
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATA_PATH: /app/data

volumes:
  databasedata:
