name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - feat/deployment

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-images:
    strategy:
      matrix:
        service: [frontend, backend, parser]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}:latest
          cache-to: type=inline

  pull-images:
    runs-on: ubuntu-latest
    needs: build-images
    permissions:
      packages: read

    steps:
      - name: Pull images to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-parser:latest


  deploy:
    runs-on: ubuntu-latest
    needs: pull-images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transfer docker-compose.prod.yaml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.prod.yaml"
          target: /home/${{ secrets.SSH_USERNAME }}/app/docker-compose.prod.yaml

      - name: Transfer nginx configs
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deployment/nginx/*"
          target: /home/${{ secrets.SSH_USERNAME }}/app/nginx

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/app
            docker compose --env DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} --env DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} --env REGISTRY=${{ env.REGISTRY }} --env IMAGE_NAME=${{ env.IMAGE_NAME }} --env TAG=latest -f docker-compose.prod.yaml up -d
